name: PR
on:
  pull_request:
    branches: [ master, main ]
permissions:
  packages: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
      - name: see generated files
        run: find ./target
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          directory: lib/build
          flags: unittests # optional
          name: coverage # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
